"""add users table

Revision ID: 41ff59639a17
Revises: 16a56d0ebbb7
Create Date: 2026-05-18 16:48:06.578623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41ff59639a17'
down_revision: Union[str, None] = '16a56d0ebbb7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AUDITOR', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.alter_column('accounts', 'code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    op.alter_column('entries', 'amount',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)
    op.alter_column('entries', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('entries', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('entries', 'amount',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
    op.alter_column('accounts', 'currency',
               existing_type=sa.VARCHAR(length=3),
               nullable=True)
    op.alter_column('accounts', 'code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
